### ISSUE TITLE
Invalid HTML for list items

### ISSUE THREAD

**Issue by nhavar** [milkycreamy22333/milkycreamy22333#1]
https://github.com/milkycreamy22333/milkycreamy22333/blob/45f0659055e793e994476ae9c2eb955e2c2d14b9/index.html#L17

list items (li) should be children of an unordered (ul) or ordered (ol) list element

```
<ul>
    <li>Learning to code</li>
    <li>Books</li>
    <li>Music</li>
</ul>
```

**Comment by milkycreamy22333** [comment]
Fixed, added ul back into the fold.
