### ISSUE TITLE
Single section for multiple levels of content

### ISSUE THREAD

**Issue by nhavar** [milkycreamy22333/milkycreamy22333#4]
Think about whether you might want to nest sections to make a clearer hierarchy around the content.
For example:

```
<section>
    <h2>What is this website for?</h2>
    <p class="p1">It's for Milk to test out his code and make sure it works</p>
    <section>
        <h3>What does Milk enjoy?</h3>
        <ul>
            <li>Learning to code</li>
            <li>Books</li>
            <li>Music</li>
         </ul?         
     </section>
</section>
```

https://github.com/milkycreamy22333/milkycreamy22333/blob/45f0659055e793e994476ae9c2eb955e2c2d14b9/index.html#L11

**Comment by milkycreamy22333** [comment]
Thought about it. Looks like a better option than what I was doing previously. Implemented.
